version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    depends_on:
      - postgres
    environment:
      HIVE_METASTORE_DB_TYPE: postgres
      HIVE_METASTORE_HOST: postgres
      HIVE_METASTORE_PORT: 5432
      HIVE_METASTORE_DB_NAME: metastore
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
    ports:
      - "9083:9083"

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    depends_on:
      - hive-metastore
    environment:
      SERVICE_NAME: hive-server
    ports:
      - "10000:10000"

volumes:
  postgres_data:
